import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useCallback, useEffect } from 'react'
import { useRouter } from 'next/router'
import { makeWorker } from '../common/WokerFactory'

export default function Home() {
  const { basePath } = useRouter()
  const getPath = useCallback((path: string) => basePath + path, [basePath])
  let textlintWorker: Worker | undefined

  useEffect(() => {
    textlintWorker = makeWorker(getPath('/textlint-worker.js'))
    textlintWorker?.postMessage({})

    //   function postToTextlint(text: string) {
    //     console.log('Post:', text)
    //     textlintWorker.postMessage({ command: 'lint', text: text, ext: '.txt' })
    //   }
    //
    //   function registerTextlintCallback() {
    //     textlintWorker.onmessage = (event) => {
    //       if (event.data.command === 'lint:result') {
    //         const messages = event.data.result.messages
    //         console.log(messages)
    //       }
    //     }
    //   }
    //
    //   if (typeof window === 'undefined') {
    //     registerTextlintCallback()
    //     postToTextlint('一文で、使える、読点の、数は、どうやら、3つらしいです。')
    //   }
  }, [getPath])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={getPath('/favicon.ico')} />
      </Head>
      <main className={styles.main}>
        <textarea
          onChange={() => {
            console.log('here')
            textlintWorker?.postMessage({})
          }}
        />
      </main>
    </>
  )
}

export function getStaticProps() {
  return { props: {} }
}
