import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useCallback, useEffect } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const { basePath } = useRouter()
  const getPath = useCallback((path: string) => basePath + path, [basePath])

  useEffect(() => {
    let textlintWorker: Worker

    if (typeof window === 'undefined') {
      textlintWorker = new Worker(getPath('/textlint-worker.js?d=3'))
    }

    function postToTextlint(text: string) {
      console.log('Post:', text)
      textlintWorker.postMessage({ command: 'lint', text: text, ext: '.txt' })
    }

    function registerTextlintCallback() {
      textlintWorker.onmessage = (event) => {
        if (event.data.command === 'lint:result') {
          const messages = event.data.result.messages
          console.log(messages)
        }
      }
    }

    if (typeof window === 'undefined') {
      registerTextlintCallback()
      postToTextlint('一文で、使える、読点の、数は、どうやら、3つらしいです。')
    }
  }, [getPath])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={getPath('/favicon.ico')} />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>こんにちは</p>
        </div>
      </main>
    </>
  )
}

export function getStaticProps() {
  return { props: {} }
}
